services:
  app:
    build:
      context: .
      platforms:
        - linux/amd64
    command: sleep infinity
    env_file:
      - .env
    volumes:
      - .:/app:cached
    ports:
      - 3100:3100
    entrypoint: sh ./docker-entrypoint-development.sh
